spring:
  datasource:
    name: blogdb
    url:  jdbc:mysql://localhost:3306/blogdb?serverTimezone=UTC
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:      hibernate:
        dialect: org.hibernate.dialect.MySQL55Dialect
        format_sql : true
server:  port: 1234